#!/usr/bin/env bash
# Build one of the haskell-miso example apps to WASM with the
# stable-haskell multi-target GHC + dual-compiler cabal.
#
# Usage (inside the container):
#   build-miso-app.sh chess
#   build-miso-app.sh solitaire
#   build-miso-app.sh both       # default
#   build-miso-app.sh help
#
# The script intentionally DOES NOT use ghc-wasm-meta's
# `wasm32-wasi-cabal` wrapper. Instead it drops a `cabal.project.local`
# next to the upstream cabal.project to route the build through our
# dual-compiler cabal — the "real" stable-haskell flow we want to
# demonstrate.
#
# Artefacts land in /home/builder/out/<app>/ for easy host extraction.

set -euo pipefail

APPS_ROOT=/home/builder/work
OUT_ROOT=/home/builder/out

# ---------------------------------------------------------------------
# Toolchain handles (all on $PATH already).
# ---------------------------------------------------------------------
WASM_GHC=wasm32-unknown-wasi-ghc

# ---------------------------------------------------------------------
# log <msg>   — colourised status line (matches the rest of the
#                stable-haskell tooling output style).
# ---------------------------------------------------------------------
log() { printf '\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()  { printf '\033[1;32m✔ %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------
# build_one <name>  — clone https://github.com/haskell-miso/<name>.git,
#                     bolt on the dual-compiler cabal.project.local,
#                     build to wasm, run post-link.mjs, stage artefacts.
# ---------------------------------------------------------------------
build_one() {
  local name="$1"
  local repo="https://github.com/haskell-miso/${name}.git"
  local src="$APPS_ROOT/${name}"
  local out="$OUT_ROOT/${name}"

  log "[$name] cloning $repo"
  rm -rf "$src"
  git clone --depth 1 "$repo" "$src"
  cd "$src"

  # The upstream cabal.project sources miso from a git tag and sets
  # +template-haskell. We layer on the dual-compiler toolchain config
  # via cabal.project.local — cabal automatically picks this up and
  # overrides nothing the upstream file already says.
  log "[$name] writing cabal.project.local (dual-compiler config)"
  cat > cabal.project.local <<EOF
-- Auto-generated by stable-haskell phase8 docker demo.
-- Routes the build through stable-haskell/cabal's dual-compiler mode:
--   build-time tools (Setup.hs, alex, happy, c2hs)  -> native ghc
--   host package compilation                         -> wasm cross ghc
with-build-compiler: ghc
with-compiler:       ${WASM_GHC}
with-hc-pkg:         ${WASM_GHC}-pkg
-- hsc2hs is auto-discovered by cabal from with-compiler's bindir;
-- spelling it out as 'with-hsc2hs' is an unknown field on cabal.project
-- so we leave it implicit.

-- Required for wasm TH evaluation (host packages must produce .so).
-- Scoped to wasm32 so native build-tool packages (happy-lib, alex)
-- still build static — that's the whole point of the Stage/Toolchain
-- split.
if arch(wasm32)
  shared: True

-- aeson's ordered-keymap drags TH into BUILD packages in a way that
-- trips up wasm cross resolution. Defensively off.
package aeson
  flags: -ordered-keymap
EOF

  log "[$name] cabal build app (this is the slow step — TH-heavy)"
  cabal build app 2>&1 | tail -n 200

  # ---------------------------------------------------------------------
  # Locate the produced .wasm. cabal's executable rule emits it under
  # dist-newstyle/build/wasm32-wasi/ghc-X/<pkg>-Y/x/app/build/app/app.wasm
  # but the exact path drifts between cabal versions — find is robust.
  # ---------------------------------------------------------------------
  local wasm
  wasm=$(find dist-newstyle -name 'app.wasm' -type f -print -quit)
  [ -n "$wasm" ] || die "[$name] no app.wasm under dist-newstyle"
  log "[$name] wasm artefact: $wasm ($(du -h "$wasm" | awk '{print $1}'))"

  # ---------------------------------------------------------------------
  # post-link.mjs — emits the JSFFI glue (ghc_wasm_jsffi.js) that the
  # browser loader uses to bridge JS<->wasm. Shipped under the wasm
  # ghc's libdir.
  # ---------------------------------------------------------------------
  local libdir
  libdir=$($WASM_GHC --print-libdir)
  log "[$name] post-link.mjs → ghc_wasm_jsffi.js"
  mkdir -p "$out"
  node "$libdir/post-link.mjs" --input "$wasm" --output "$out/ghc_wasm_jsffi.js"

  # ---------------------------------------------------------------------
  # Stage static/ + the .wasm into $OUT_ROOT/<name>/. End user can copy
  # this directory verbatim into a webserver and the page works.
  # ---------------------------------------------------------------------
  if [ -d static ]; then
    cp -r static/. "$out/"
  fi
  cp "$wasm" "$out/app.wasm"

  # ---------------------------------------------------------------------
  # Patch the staged index.js. The upstream chess + solitaire launchers
  # predate miso 1.11 / GHC 9.14's RTS init contract and ship an old
  # browser_wasi_shim. See ../index.js.patch's header for the rationale;
  # it's a two-hunk minimal-edit unified diff that GNU patch applies in
  # under a millisecond.
  # ---------------------------------------------------------------------
  log "[$name] applying index.js.patch (browser_wasi_shim 0.4.2 + jsffi init)"
  # -p2 strips both `a/` and `static/` from the patch's left labels
  # since we apply against the staged-flat $out/index.js (the upstream
  # path is static/index.js, but we copied it directly to $out/).
  patch -p2 -d "$out" --posix -i /home/builder/index.js.patch \
        --backup-if-mismatch=no

  ok "[$name] built: $out/app.wasm ($(du -h "$out/app.wasm" | awk '{print $1}'))"
}

usage() {
  cat <<EOF
Usage: build-miso-app.sh {chess|solitaire|both|help}

Builds the named haskell-miso example app(s) to WASM using our
stable-haskell multi-target GHC + dual-compiler cabal. Output goes to
/home/builder/out/<app>/ — mount that to your host to extract.
EOF
}

case "${1:-both}" in
  chess)     build_one chess     ;;
  solitaire) build_one solitaire ;;
  both)      build_one chess; build_one solitaire ;;
  help|-h|--help) usage ;;
  *) usage; exit 2 ;;
esac
